version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    networks:
      - app-network
    volumes:
      - ./db/:/var/lib/mysql
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  app:
    container_name: app
    build: 
      context: node
    entrypoint: dockerize -wait tcp://db:3306 /bin/sh -c "npm ci && node index.js"
    tty: true
    volumes:
      - ./node/app:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    tty: true
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
